# Create virtual environment with command:
#
#   $ CONDA_OVERRIDE_CUDA=11.8 conda env create --file conda-recipe.yaml
#

name: BlackDAN
channels:
  - huggingface
  - pytorch
  - nvidia/label/cuda-11.8.0
  - defaults
  - conda-forge
dependencies:
  - python = 3.11
  - pip

  - pytorch::pytorch >= 2.0
  - pytorch::pytorch-mutex =*=*cuda*
  - transformers >= 4.37
  - datasets
  - tokenizers >= 0.13.3
  - sentencepiece
  - tensorboard
  - wandb
  - pip:
      - accelerate
      - deepspeed

  - nvidia/label/cuda-11.8.0::cuda-toolkit = 11.8

  - optree
  - scipy
  - nvitop
  - matplotlib-base
  - rich
  - tqdm
  - typing-extensions
  - openai
  - nltk